---
title: "Metadatos"
author: "Manuel Quintana Montero"
date: "2024-11-04"
output: html_document
---

#METABOLOMICS WORKBENCH ofiehn_20130123_9589761_mwtab.txt DATATRACK_ID:34 STUDY_ID:ST000002 ANALYSIS_ID:AN000002 PROJECT_ID:PR000002
VERSION             	1
CREATED_ON          	2016-09-17
#PROJECT
PR:PROJECT_TITLE                 	Intestinal Samples II pre/post transplantation
PR:PROJECT_TYPE                  	Human intestinal samples
PR:PROJECT_SUMMARY               	Intestinal Samples II pre/post transplantation
PR:INSTITUTE                     	University of California, Davis
PR:DEPARTMENT                    	Davis Genome Center
PR:LABORATORY                    	Fiehn
PR:LAST_NAME                     	Fiehn
PR:FIRST_NAME                    	Oliver
PR:ADDRESS                       	451 E. Health Sci. Drive, Davis, California 95616, USA
PR:EMAIL                         	ofiehn@ucdavis.edu
PR:PHONE                         	-
#STUDY
ST:STUDY_TITLE                   	Intestinal Samples II pre/post transplantation
ST:STUDY_TYPE                    	MS analysis
ST:STUDY_SUMMARY                 	Intestinal Samples II pre/post transplantation
ST:INSTITUTE                     	University of California, Davis
ST:DEPARTMENT                    	Davis Genome Center
ST:LABORATORY                    	Fiehn
ST:LAST_NAME                     	Hartman
ST:FIRST_NAME                    	Amber
ST:ADDRESS                       	451 E. Health Sci. Drive, Davis, California 95616, USA
ST:EMAIL                         	-
ST:PHONE                         	-
ST:NUM_GROUPS                    	2
ST:TOTAL_SUBJECTS                	12
#SUBJECT
SU:SUBJECT_TYPE                  	Human
SU:SUBJECT_SPECIES               	Homo sapiens
SU:TAXONOMY_ID                   	9606
SU:SPECIES_GROUP                 	Human
#SUBJECT_SAMPLE_FACTORS:         	SUBJECT(optional)[tab]SAMPLE[tab]FACTORS(NAME:VALUE pairs separated by |)[tab]Additional sample data
SUBJECT_SAMPLE_FACTORS           	-	LabF_684508	Transplantation:After transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684512	Transplantation:After transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684516	Transplantation:After transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684520	Transplantation:After transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684524	Transplantation:After transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684528	Transplantation:After transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684483	Transplantation:Before transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684487	Transplantation:Before transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684491	Transplantation:Before transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684495	Transplantation:Before transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684499	Transplantation:Before transplantation	
SUBJECT_SAMPLE_FACTORS           	-	LabF_684503	Transplantation:Before transplantation	
#COLLECTION
CO:COLLECTION_SUMMARY            	-
CO:SAMPLE_TYPE                   	Tissue
#TREATMENT
TR:TREATMENT_SUMMARY             	-
TR:TREATMENT_PROTOCOL_COMMENTS   	Before transplantation | After transplanation
#SAMPLEPREP
SP:SAMPLEPREP_SUMMARY            	-
SP:EXTRACTION_METHOD             	Extraction: Proteomics 2004, 4, 78-83; Splitratio: splitless 25 purge
#CHROMATOGRAPHY
CH:CHROMATOGRAPHY_TYPE           	GC
CH:INSTRUMENT_NAME               	Agilent 6890N
CH:COLUMN_NAME                   	-
#ANALYSIS
AN:ANALYSIS_TYPE                 	MS
#MS
MS:MS_COMMENTS                   	-
MS:INSTRUMENT_NAME               	Leco Pegasus III GC TOF
MS:INSTRUMENT_TYPE               	GC-TOF
MS:MS_TYPE                       	EI
MS:ION_MODE                      	POSITIVE
#MS_METABOLITE_DATA
MS_METABOLITE_DATA:UNITS         	Peak height